### ISSUE TITLE
function uuid.NewV1() will return multi value

### ISSUE THREAD

**Issue by SecurityNeo** [letgoapp/krakend-consul#3]
Hi,
service := &api.AgentServiceRegistration{
		Name: cfg.Name,
		Port: cfg.Port,
		Tags: cfg.Tags,
		ID: uuid.NewV1().String(),
	}

actually,function uuid.NewV1() will return tow value,so maybe we clould change like this:

	Uuid, _ := uuid.NewV1()
	service := &api.AgentServiceRegistration{
		Name: cfg.Name,
		Port: cfg.Port,
		Tags: cfg.Tags,
		ID: Uuid.String(),
	}

BTW,I have no permission to access 'https://github.com/devopsfaith/krakend-consul.git',so please confirm this problem,thank you

Best Regards!
Neo

**Comment by kpacha** [comment]
hi @SecurityNeo and welcome to the KrakenD community!

This package is using the uuid.go v1.2.0 and, in this version, the uuid generators do return a single UUID struct, without the error: https://github.com/satori/go.uuid/blob/v1.2.0/generator.go#L49-L51

cheers
